apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.global.namespace}}
  name: drill-service
spec:
  ports:
    - name: http
      port: 8047
    - name: userport
      port: 31010
    - name: controlport
      port: 31011
    - name: dataport
      port: 31012
  selector:
    app: drill-app
