kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: drill-crb
subjects:
  - kind: ServiceAccount
    name: drill-sa
    namespace: {{.Values.namespace}}
roleRef:
  kind: ClusterRole
  name: drill-crole
  apiGroup: rbac.authorization.k8s.io

