kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: {{.Values.namespace}}
  name: drill-crole
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'

