kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: drill-rb
subjects:
  - kind: ServiceAccount
    name: drill-sa
    namespace:
      '[object Object]': null
roleRef:
  kind: Role
  name: drill-role
  apiGroup: rbac.authorization.k8s.io

