apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{.Values.global.namespace}}
  name: {{.Values.drill.id}}-drillbit
spec:
  serviceName: drill-service
  replicas: {{.Values.drill.count}}
  selector: 
    matchLabels: 
      app: drill-app
  template:
    metadata:
      labels:
        app: drill-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - drill-app
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: drill-sa
      containers:
        - name: drill-pod
          imagePullPolicy: Always
          image: {{.Values.drill.image}}
          ports:
            - containerPort: 8047
              name: http
            - containerPort: 31010
              name: userport
            - containerPort: 31011
              name: controlport
            - containerPort: 31012
              name: dataport
          env:
            - name: KUBERNETES_CONTAINER
              value: "true"
            - name: POD_NAME
              value: "drill-bit"
            - name: DRILL_ZK_ROOT
              value: {{.Values.drill.id}}
            - name: DRILL_MAX_MEMORY
              value: {{.Values.drill.memory}}
            - name: DRILL_HTTP_PORT
              value: "8047"
            - name: DRILL_USER_SERVER_PORT
              value: "31010"
      initContainers:
        - name: zk-available
          image: busybox
          command: ['sh', '-c', 'until nc -z zk-service 2181; do echo Waiting for ZK to come up; sleep 5; done; ']
