apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.global.namespace}}
  name: drill-service
spec:
  ports:
    - name: http
      port: {{ .Values.drill.httpPort }}
    - name: userport
      port: {{ .Values.drill.userServerPort }}
    - name: controlport
      port: {{ add .Values.drill.userServerPort 1 }}
    - name: dataport
      port: {{ add .Values.drill.userServerPort 2 }}
  selector:
    app: drill-app
