#!/usr/bin/env bash

if [[ $MIRROR_ENV == "" ]]
then
  docker build --build-arg VERSION=${VERSION_ENV} -t agirish/drill:${VERSION_ENV} -t agirish/drill:${VERSION_ENV} .
else
  docker build --build-arg VERSION=${VERSION_ENV} --build-arg MIRROR=${MIRROR_ENV} -t agirish/drill:${VERSION_ENV} -t agirish/drill:${VERSION_ENV} .
fi