repo: hub.docker.com/u/

global:
  namespace: default

drill:
  id: drillcluster1
  count: 1
  memory: 5Gi
  cpu: 4000m
  image: agirish/drill:1.17.0
  httpPort: 8047
  userServerPort: 31010
  livenessProbe:
    exec:
      command:
        - sh
        - -c
        - /opt/drill/bin/isLive.sh
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 10
  readinessProbe:
    exec:
      command:
        - sh
        - -c
        - /opt/drill/bin/isReady.sh
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 5

zookeeper:
  id: zk
  memory: 2Gi
  cpu: 500m
  image: agirish/zookeeper:3.6.0
