repo: hub.docker.com/u/

global:
  namespace: default

drill:
  id: drillcluster1
  # The following environments are currently supported: [gke, on-prem]
  environment: gke
  count: 2
  memory: 5Gi
  cpu: 4000m
  image: agirish/drill:1.17.0
  httpPort: 8047
  userServerPort: 31010
  livenessProbe:
    exec:
      command:
        - sh
        - -c
        - /opt/drill/bin/isLive.sh
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 10
  readinessProbe:
    exec:
      command:
        - sh
        - -c
        - /opt/drill/bin/isReady.sh
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 5
  lifecycle:
    preStop:
      exec:
        command:
          - sh
          - -c
          - /opt/drill/bin/preStop.sh
  terminationGracePeriodSeconds: 60

zookeeper:
  id: zk
  memory: 2Gi
  cpu: 500m
  image: agirish/zookeeper:3.6.0
