kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: {{.Values.namespace}}
  name: zk-rb
subjects:
  - kind: ServiceAccount
    name: zk-sa
    namespace: {{.Values.namespace}}
roleRef:
  kind: Role
  name: zk-role
  apiGroup: rbac.authorization.k8s.io

