kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: {{.Values.global.namespace}}
  name: zk-role
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'

