apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.global.namespace}}
  name: zk-service
spec:
  ports:
    - name: client
      port: 2181
    - name: server
      port: 2888
    - name: leader-election
      port: 3888
  selector:
    app: zk-quorum
